name: Release Application

on:
  release:
    types: [created]

jobs:
  upload-release-assets:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload Executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Cahier_de_textes.exe
        asset_name: Cahier_de_textes.exe
        asset_content_type: application/octet-stream
    - name: Upload Distribution Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Cahier_de_textes_distribution.zip
        asset_name: Cahier_de_textes_distribution.zip
        asset_content_type: application/zip
